services:
  # rabbitmq:
  #   image: rabbitmq:3.13-management-alpine
  #   container_name: 'rabbitmq'
  #   ports:
  #     - 5672:5672
  #     - 15672:15672 #ui
  #   tmpfs:
  #     - /var/lib/rabbitmq/
  #     - /var/log/rabbitmq 
  # cassandra:
  #   image: cassandra:latest
  #   container_name: cassandradb
  #   ports:
  #     - 9042:9042
  #   environment:
  #     - CASSANDRA_USER=admin
  #     - CASSANDRA_PASSWORD=password
  #   tmpfs:
  #     - /var/lib/cassandra/
  authdb:
    image: postgres:alpine
    ports:
      - 5432:5432
    tmpfs: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
  
  gateway:
    build:
      dockerfile: ./gateway/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - auth
    restart: always

  counterdb:
    image: postgres:alpine
    ports:
      - 5433:5433
    tmpfs: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: counter
    command: -p 5433
  
  auth:
    build: 
      dockerfile: ./auth/Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - authdb
    restart: always

  counter:
    build: 
      dockerfile: ./counter/Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - counterdb
    restart: always
